// <auto-generated />
using System;
using ListaTarefaKanban_Resitory;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ListaTarefaKanban_Repository.Migrations
{
    [DbContext(typeof(KanbanContext))]
    [Migration("20190405195053_IdTabelaTarefa")]
    partial class IdTabelaTarefa
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("ListaTarefaKanban_Domain.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DataPrevInicio");

                    b.Property<DateTime?>("DataPrevTermino");

                    b.Property<DateTime?>("DataRealInicio");

                    b.Property<DateTime?>("DataRealTermino");

                    b.Property<double>("EsforcoPrev");

                    b.Property<double>("EsforcoReal");

                    b.Property<int>("Prioridade");

                    b.Property<int>("Status");

                    b.Property<string>("Titulo");

                    b.Property<int?>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Tarefas");
                });

            modelBuilder.Entity("ListaTarefaKanban_Domain.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ListaTarefaKanban_Domain.Tarefa", b =>
                {
                    b.HasOne("ListaTarefaKanban_Domain.Usuario", "Responsavel")
                        .WithMany()
                        .HasForeignKey("UsuarioId");
                });
#pragma warning restore 612, 618
        }
    }
}
